### ISSUE TITLE
Program not properly terminating

### ISSUE THREAD

**Issue by xesdoog** [NiiV3AU/YMU#3]
When exiting YMU, it doesn't kill its own process. Instead it keeps running in the background. I tried adding exit checks but nothing seemed to fix the issue.

![image](https://github.com/NiiV3AU/YMU/assets/66764345/3bc2bb79-e37a-4306-a351-85243796eba7)

**Comment by NiiV3AU** [comment]
Im going to look into it. Maybe is there a CTkTopLevel (more info frame) still running or something.

**Comment by NiiV3AU** [comment]
I cant find a solution myself 😭  , but my guess is that a while True loop is still running in the background, even after the application itself is destroyed. I hope someone else sees the issue to help us out!

**Comment by xesdoog** [comment]
> I cant find a solution myself 😭 , but my guess is that a while True loop is still running in the background, even after the application itself is destroyed. I hope someone else sees the issue to help us out!

I think it has to do with the animated text because if you run the program on debug mode through your IDE, when you close the window the ani_start thread throws an error. Could you please try to disable it temporarily and check if the program terminates correctly or not?

**Comment by NiiV3AU** [comment]
> Could you please try to disable it temporarily and check if the program terminates correctly or not?

Yeah Im gonna try it as soon as Im back at my computer

**Comment by NiiV3AU** [comment]
I've fixed it! Just needed to add a parameter to all Threads! 
Before: `Thread(target=func).start()`
Now:  `Thread(target=func, daemon=True).start()`
The daemon parameter is set to `None` by default which makes the thread as far as I understand independent from the mainthread. With `daemon=True` it's linked to the mainthread and it terminates together with the mainthread.
